apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |-
        - "Add controller.metrics.serviceMonitor.annotations in Helm chart"
        - "fix(labels): use complete labels variable on default-backend deployment"
        - "chart: allow setting allocateLoadBalancerNodePorts (#10693)"
        - "[release-1.9] feat(helm): add documentation about metric args (#10695)"
        - "Update Ingress-Nginx version controller-v1.9.5"
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.9.5
    created: "2024-01-30T09:23:43.957667179Z"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 0e2b1dc67321c6bdc346f43d75683e09a0a4caedb6e55ea2d44d450c23655f72
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.9.0.tgz
    version: 4.9.0
  nginx:
  - annotations:
      category: Infrastructure
      images: |
        - name: git
          image: docker.io/bitnami/git:2.43.0-debian-11-r5
        - name: nginx-exporter
          image: docker.io/bitnami/nginx-exporter:1.1.0-debian-11-r0
        - name: nginx
          image: docker.io/bitnami/nginx:1.25.3-debian-11-r4
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.25.3
    created: "2024-01-30T09:23:43.960177297Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: NGINX Open Source is a web server that can be also used as a reverse
      proxy, load balancer, and HTTP cache. Recommended for high-demanding sites due
      to its ability to provide faster content.
    digest: 3b3724b9a517e86f19ed1b13195f6edf80deed8426d9cdca32950a767c722033
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: nginx
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/nginx
    urls:
    - nginx-15.9.0.tgz
    version: 15.9.0
generated: "2024-01-30T09:23:43.952965729Z"
